name: cambridge_school
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '3.5.4'

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  #---------- UI & Animation ----------#
  flutter_svg: ^2.0.11
  shimmer: ^3.0.0
  percent_indicator: ^4.2.3
  carousel_slider: ^5.0.0
  flutter_native_splash: ^2.4.2
  lottie: ^3.2.0
  smooth_page_indicator: ^1.1.0
  readmore: ^2.2.0
  autocomplete_textfield: ^2.0.1

  #---------- Charts ----------#
  fl_chart: ^0.69.0

  #---------- Navigation & Routing ----------#
  qr_flutter: ^4.1.0


  #---------- State Management ----------#
  get: ^4.6.6
  get_storage: ^2.1.1

  #---------- Firebase ----------#
  firebase_core: ^2.25.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.0
  firebase_database: ^10.4.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.9.4
  firebase_app_check: ^0.2.2+7

  #---------- Media & File Handling ----------#
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  video_player: ^2.8.2
  audio_waveforms: ^1.0.3
  path_provider: ^2.0.14
  file_picker: ^6.1.1
  #  table_calendar: ^3.0.9
  # easy_date_timeline: ^1.0.2
  #  photo_view: ^0.14.0

  #---------- Utilities ----------#
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.1.14
  form_field_validator: ^1.1.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  contacts_service: ^0.6.3
  rxdart: ^0.27.7
  emoji_picker_flutter: ^2.2.0
  hive_flutter: ^1.1.0
  dio: ^5.8.0+1
  http: ^1.3.0
  csv: ^6.0.0
  uuid: ^4.5.1
  sticky_headers: ^0.3.0+2
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.4.1
  nanoid: ^1.0.0
  transformable_list_view: ^0.6.0
  connectivity_plus: ^6.1.3
  faker: ^2.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/images/illustrations/
    - assets/images/illustrations/empty_state_illustration/
    - assets/logos/
    - assets/animations/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800