class Subject {
  final String name;
  final List<String> icons;

  Subject({required this.name, required this.icons});
}

final List<Subject> subjects = [
  // Core Academic Subjects - Mathematics
  Subject(name: 'Mathematics', icons: ['➕', '➗', '📐']),
  Subject(name: 'Arithmetic', icons: ['🔢', '➖', '➗']),
  Subject(name: 'Pre-Algebra', icons: ['➕', '🔣', '📏']),
  Subject(name: 'Algebra', icons: ['➕', '🔣', '📏']),
  Subject(name: 'Algebra I', icons: ['➕', '🔣', '📏']),
  Subject(name: 'Algebra II', icons: ['➕', '🔣', '📏']),
  Subject(name: 'Geometry', icons: ['📐', '📏', '🧮']),
  Subject(name: 'Trigonometry', icons: ['📐', '📈', '🧮']),
  Subject(name: 'Pre-Calculus', icons: ['📊', '📉', '🔢']),
  Subject(name: 'Calculus', icons: ['📊', '📉', '🔢']),
  Subject(name: 'Statistics', icons: ['📊', '📈', '🧮']),
  Subject(name: 'Discrete Mathematics', icons: ['➕', '🧮', '🔢']),
  Subject(name: 'Linear Algebra', icons: ['➕', '🧮', '🔢']),

  // Core Academic Subjects - English/Language Arts
  Subject(name: 'English', icons: ['📖', '✍️', '📝']),
  Subject(name: 'Language Arts', icons: ['📖', '✍️', '📝']),
  Subject(name: 'Reading', icons: ['📖', '🧠', '🗣️']),
  Subject(name: 'Writing', icons: ['✍️', '🖊️', '📝']),
  Subject(name: 'English Grammar', icons: ['📚', '📝', '🔤']),
  Subject(name: 'English Literature', icons: ['📜', '📖', '🎭']),
  Subject(name: 'American Literature', icons: ['📜', '📖', '🇺🇸']),
  Subject(name: 'British Literature', icons: ['📜', '📖', '🇬🇧']),
  Subject(name: 'World Literature', icons: ['📜', '📖', '🌍']),
  Subject(name: 'Creative Writing', icons: ['✍️', '🖊️', '🧠']),
  Subject(name: 'Composition', icons: ['✍️', '📝', '📚']),
  Subject(name: 'Rhetoric', icons: ['🗣️', '✍️', '🧠']),
  Subject(name: 'Vocabulary', icons: ['🔤', '📚', '🧠']),
  Subject(name: 'Reading Comprehension', icons: ['📖', '🤔', '🧠']),

  // Core Academic Subjects - Hindi
  Subject(name: 'Hindi', icons: ['📜', '🖋️', '📚']),
  Subject(name: 'Hindi Grammar (व्याकरण)', icons: ['📝', '📚', '🖋️']),
  Subject(name: 'Hindi Literature', icons: ['📖', '📜', '🕉️']),

  // Core Academic Subjects - Science
  Subject(name: 'Science', icons: ['🔬', '🧪', '🧬']),
  Subject(name: 'General Science', icons: ['🔬', '🌍', '🧠']),
  Subject(name: 'Life Science', icons: ['🌱', '🧬', '🌍']),
  Subject(name: 'Physical Science', icons: ['⚛️', '🧪', '🌍']),
  Subject(name: 'Environmental Science (EVS)', icons: ['🌳', '🌿', '🌍']),
  Subject(name: 'Earth Science', icons: ['🌎', '🌋', '🏔️']),
  Subject(name: 'Physics', icons: ['⚛️', '📡', '🔭']),
  Subject(name: 'Chemistry', icons: ['🧪', '🧫', '⚗️']),
  Subject(name: 'Biology', icons: ['🌱', '🧬', '🧫']),
  Subject(name: 'Zoology', icons: ['🦓', '🦒', '🐅']),
  Subject(name: 'Botany', icons: ['🌿', '🌻', '🌳']),
  Subject(name: 'Anatomy & Physiology', icons: ['🫀', '🧠', '🦴']),
  Subject(name: 'Marine Biology', icons: ['🌊', '🐠', '🐳']),
  Subject(name: 'Astronomy', icons: ['🌌', '🔭', '🪐']),
  Subject(name: 'Geology', icons: ['⛰️', '⛏️', '🌍']),

  // Core Academic Subjects - Social Studies
  Subject(name: 'Social Studies', icons: ['🌍', '🕰️', '📜']),
  Subject(name: 'History', icons: ['🏺', '📜', '🕰️']),
  Subject(name: 'World History', icons: ['🌍', '📜', '🕰️']),
  Subject(name: 'US History', icons: ['🇺🇸', '📜', '🕰️']),
  Subject(name: 'European History', icons: ['🇪🇺', '📜', '🕰️']),
  Subject(name: 'Geography', icons: ['🗺️', '🌎', '🧭']),
  Subject(name: 'Civics', icons: ['🏛️', '📋', '📊']),
  Subject(name: 'Political Science', icons: ['🏛️', '📋', '📊']),
  Subject(name: 'Economics', icons: ['💹', '📈', '📊']),
  Subject(name: 'Microeconomics', icons: ['💹', '📈', '📊']),
  Subject(name: 'Macroeconomics', icons: ['💹', '📈', '📊']),
  Subject(name: 'Psychology', icons: ['🧠', '📚', '🧮']),
  Subject(name: 'Sociology', icons: ['🧑‍🤝‍🧑', '🌐', '📚']),
  Subject(name: 'Anthropology', icons: ['🧑‍🤝‍🧑', '🌍', '🏺']),
  Subject(name: 'Archaeology', icons: ['⛏️', '🏺', '📜']),
  Subject(name: 'World Affairs', icons: ['🌍', '📰', '🗣️']),

  // Languages
  Subject(name: 'Sanskrit', icons: ['📜', '🕉️', '🖋️']),
  Subject(name: 'Regional Languages', icons: ['🗣️', '📖', '📝']),
  Subject(name: 'Foreign Languages', icons: ['🌐', '🗣️', '📖']),
  Subject(name: 'Spanish', icons: ['🇪🇸', '🗣️', '📖']),
  Subject(name: 'French', icons: ['🇫🇷', '🗣️', '📖']),
  Subject(name: 'German', icons: ['🇩🇪', '🗣️', '📖']),
  Subject(name: 'Chinese (Mandarin)', icons: ['🇨🇳', '🗣️', '📖']),
  Subject(name: 'Japanese', icons: ['🇯🇵', '🗣️', '📖']),
  Subject(name: 'Latin', icons: ['🏛️', '📜', '📖']),
  Subject(name: 'Sign Language', icons: ['🤟', '🗣️', '🙌']),

  // Electives & Special Subjects - Technology
  Subject(name: 'Computer Science/IT', icons: ['💻', '🖥️', '⌨️']),
  Subject(name: 'Programming', icons: ['💻', '🧮', '👨‍💻']),
  Subject(name: 'Web Development', icons: ['🌐', '💻', '🖥️']),
  Subject(name: 'Data Science', icons: ['📊', '📈', '🧮']),
  Subject(name: 'Robotics', icons: ['🤖', '⚙️', '💻']),
  Subject(name: 'Digital Literacy', icons: ['📱', '💻', '🌐']),
  Subject(name: 'Computer Applications', icons: ['💻', '🖱️', '🗂️']),
  Subject(name: 'Multimedia', icons: ['🎬', '🎧', '🖼️']),
  Subject(name: 'Python Programming', icons: ['🐍', '💻', '🧮']),
  Subject(name: 'Java Programming', icons: ['☕', '💻', '🧮']),
  Subject(name: 'C++ Programming', icons: ['💻', '🧮', '➕']),
  Subject(name: 'Game Development', icons: ['🎮', '💻', '🕹️']),
  Subject(name: 'Cybersecurity', icons: ['🔒', '💻', '🌐']),
  Subject(name: 'Database Management', icons: ['🗄️', '💻', '🧮']),
  Subject(name: 'Networking', icons: ['🌐', '💻', '📡']),

  // Electives & Special Subjects - Arts & Humanities
  Subject(name: 'Moral Science/Value Education', icons: ['🙏', '🕊️', '📚']),
  Subject(name: 'Arts', icons: ['🎨', '🖌️', '🖼️']),
  Subject(name: 'Drawing', icons: ['🖍️', '🎨', '📝']),
  Subject(name: 'Painting', icons: ['🎨', '🖌️', '🖼️']),
  Subject(name: 'Music', icons: ['🎵', '🎶', '🎹']),
  Subject(name: 'Vocal Music', icons: ['🎤', '🎵', '🎶']),
  Subject(name: 'Instrumental Music', icons: ['🎵', '🎹', '🎸']),
  Subject(name: 'Choir', icons: ['🎶', '🧑‍🤝‍🧑', '🎤']),
  Subject(name: 'Band', icons: ['🎺', '🥁', '🎷']),
  Subject(name: 'Orchestra', icons: ['🎻', '🎵', '🎶']),
  Subject(name: 'Art History', icons: ['🏺', '🖼️', '🕰️']),
  Subject(name: 'Drama/Theatre', icons: ['🎭', '🎬', '📽️']),
  Subject(name: 'Dance', icons: ['💃', '🕺', '🎶']),
  Subject(name: 'Fine Arts', icons: ['🎨', '🖼️', '🖌️']),
  Subject(name: 'Photography', icons: ['📸', '🖼️', '💡']),
  Subject(name: 'Film Studies', icons: ['🎬', '📽️', '🍿']),
  Subject(name: 'Creative Writing', icons: ['✍️', '🖊️', '🧠']),
  Subject(name: 'Journalism', icons: ['📰', '✍️', '🎤']),

  // Electives & Special Subjects - Practical & Life Skills
  Subject(name: 'Physical Education (PE)', icons: ['🏃‍♂️', '🏀', '🤸‍♀️']),
  Subject(name: 'Health', icons: ['⚕️', '🍎', '🧠']),
  Subject(name: 'Home Science', icons: ['🍲', '🧵', '🏠']),
  Subject(name: 'Business Studies', icons: ['💼', '📈', '📊']),
  Subject(name: 'Accountancy', icons: ['📊', '📉', '📑']),
  Subject(name: 'Economics', icons: ['💹', '📈', '📊']),
  Subject(name: 'Philosophy', icons: ['🧠', '📜', '🕊️']),
  Subject(name: 'Work Education', icons: ['🛠️', '📐', '✂️']),
  Subject(name: 'Design & Technology', icons: ['🛠️', '📏', '📐']),
  Subject(name: 'Agriculture', icons: ['🌾', '🚜', '🌱']),
  Subject(name: 'Entrepreneurship', icons: ['🚀', '💡', '📈']),
  Subject(name: 'Retail Management', icons: ['🛍️', '📦', '💳']),
  Subject(name: 'Tourism & Hospitality', icons: ['🏨', '✈️', '🍽️']),
  Subject(name: 'Library Studies', icons: ['📚', '📖', '📂']),
  Subject(name: 'Crafts', icons: ['✂️', '🧶', '🎨']),
  Subject(name: 'Yoga', icons: ['🧘‍♂️', '🧘‍♀️', '🕉️']),
  Subject(name: 'Food & Nutrition', icons: ['🍎', '🍲', '🥗']),
  Subject(name: 'Financial Literacy', icons: ['💰', '📈', '📊']),
  Subject(name: 'Ethics & Life Skills', icons: ['🤝', '🧠', '📚']),
  Subject(name: 'Home Economics', icons: ['🏠', '🧺', '🍽️']),
  Subject(name: 'Woodworking', icons: ['🪵', '🔨', '🪚']),
  Subject(name: 'Metalworking', icons: ['🔩', '⚙️', '🔥']),
  Subject(name: 'Personal Finance', icons: ['💰', '📈', '🏦']),
  Subject(name: 'Civic Education', icons: ['🗳️', '🏛️', '📜']),

  // Electives & Special Subjects - Vocational & Technical
  Subject(name: 'Automotive Technology', icons: ['🚗', '🔧', '🔩']),
  Subject(name: 'Carpentry', icons: ['🔨', '🪚', '🪵']),
  Subject(name: 'Electrical Technology', icons: ['💡', '⚡', '🔌']),
  Subject(name: 'Welding', icons: ['🔥', '🔩', '⚙️']),
  Subject(name: 'HVAC (Heating, Ventilation, Air Conditioning)', icons: ['❄️', '🔥', '⚙️']),
  Subject(name: 'Plumbing', icons: ['🚰', '🔧', '🏠']),
  Subject(name: 'Cosmetology', icons: ['💇‍♀️', '💅', '💄']),
  Subject(name: 'Culinary Arts', icons: ['🍳', '🍽️', '🍲']),
  Subject(name: 'Graphic Design', icons: ['🎨', '💻', '🖌️']),
  Subject(name: 'Fashion Design', icons: ['👗', '🧵', '✂️']),

  // Other Specialized Subjects
  Subject(name: 'Biotechnology', icons: ['🧬', '🧫', '🔬']),
  Subject(name: 'Public Speaking', icons: ['🎤', '🧑‍💼', '🗣️']),
  Subject(name: 'Debate', icons: ['🗣️', '🤔', '📋']),
  Subject(name: 'Life Skills', icons: ['🤝', '🧠', '🧘‍♂️']),
  Subject(name: 'Disaster Management', icons: ['🆘', '🌪️', '🚨']),
  Subject(name: 'Self-Defense', icons: ['🥋', '🤼‍♂️', '🛡️']),
  Subject(name: 'First Aid', icons: ['🚑', '🩹', '🩺']),
  Subject(name: 'Gardening', icons: ['🌿', '🌻', '🌱']),
  Subject(name: 'Spoken English', icons: ['🗣️', '🎤', '📖']),
  Subject(name: 'Communication Skills', icons: ['🗣️', '🤝', '🧠']),
  Subject(name: 'Study Skills', icons: ['📚', '🧠', '📝']),
  Subject(name: 'Leadership', icons: ['👑', '🧑‍💼', '🗣️']),

  //Special Education
  Subject(name: 'Special Education', icons: ['❤️', '📚', '🧑‍🏫']),
  Subject(name: 'Adaptive Physical Education', icons: ['❤️', '🏃‍♂️', '🤸‍♀️']),
];