// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjhX-uL5e4srB83yliydhKe1wkeuoD7UQ',
    appId: '1:698643999415:web:063f6cac6d8ec1a78efb32',
    messagingSenderId: '698643999415',
    projectId: 'cambridge-school-dumraon',
    authDomain: 'cambridge-school-dumraon.firebaseapp.com',
    storageBucket: 'cambridge-school-dumraon.firebasestorage.app',
    measurementId: 'G-FWF5T8T30F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYU9lDiSavoxmNiC0dLvAIOsfAHrAEZto',
    appId: '1:698643999415:android:71d7ce2ac0052a688efb32',
    messagingSenderId: '698643999415',
    projectId: 'cambridge-school-dumraon',
    storageBucket: 'cambridge-school-dumraon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj1fuPjDVaeyr_UnYfcoRgRePVDxfE5iw',
    appId: '1:698643999415:ios:6a90209dc5e4fff48efb32',
    messagingSenderId: '698643999415',
    projectId: 'cambridge-school-dumraon',
    storageBucket: 'cambridge-school-dumraon.firebasestorage.app',
    iosBundleId: 'com.stex.cambridgeSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj1fuPjDVaeyr_UnYfcoRgRePVDxfE5iw',
    appId: '1:698643999415:ios:6a90209dc5e4fff48efb32',
    messagingSenderId: '698643999415',
    projectId: 'cambridge-school-dumraon',
    storageBucket: 'cambridge-school-dumraon.firebasestorage.app',
    iosBundleId: 'com.stex.cambridgeSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjhX-uL5e4srB83yliydhKe1wkeuoD7UQ',
    appId: '1:698643999415:web:4f0c4a9a674f623f8efb32',
    messagingSenderId: '698643999415',
    projectId: 'cambridge-school-dumraon',
    authDomain: 'cambridge-school-dumraon.firebaseapp.com',
    storageBucket: 'cambridge-school-dumraon.firebasestorage.app',
    measurementId: 'G-0W63SJWVYZ',
  );
}
