import '../../../roles_manager.dart';

class ObjectList{
  static final List<RoleDefinition> roleDefinitions = [
    RoleDefinition(
      role: UserRole.superAdmin,
      permissions: [
        AppPermission.manageUsers,
        AppPermission.manageTeachers,
        AppPermission.manageStudents,
        AppPermission.manageAttendance,
        AppPermission.manageExams,
        AppPermission.viewReports,
        AppPermission.manageFinance,
        AppPermission.manageTransport,
        AppPermission.manageLibrary,
        AppPermission.viewStudents,
        AppPermission.assignHomework,
        AppPermission.submitHomework,
        AppPermission.viewResults,
        AppPermission.viewSchedule,
        AppPermission.viewExams,
        AppPermission.payFees,
        AppPermission.viewChildReports,
        AppPermission.viewAttendance,
        AppPermission.viewRoutes,
        AppPermission.markTransportAttendance,
        AppPermission.createAnnouncements,
        AppPermission.viewAnnouncements,
        AppPermission.manageEvents,
        AppPermission.viewEvents,
        AppPermission.manageClassrooms,
        AppPermission.manageSubjects,
        AppPermission.viewSubjects,
        AppPermission.sendNotifications,
        AppPermission.manageTimetable,
        AppPermission.viewTimetable,
        AppPermission.manageAssignments,
        AppPermission.viewAssignments,
        AppPermission.manageStudyMaterials,
        AppPermission.viewStudyMaterials,
        AppPermission.communicateWithParents,
        AppPermission.manageStudentBehavior,
        AppPermission.viewStudentBehavior,
        AppPermission.manageFees,
      ],
    ),
    RoleDefinition(
      role: UserRole.admin,
      permissions: [
        AppPermission.manageUsers,
        AppPermission.manageTeachers,
        AppPermission.manageStudents,
        AppPermission.manageAttendance,
        AppPermission.manageExams,
        AppPermission.viewReports,
        AppPermission.manageFinance,
        AppPermission.manageTransport,
        AppPermission.manageLibrary,
        AppPermission.viewStudents,
        AppPermission.createAnnouncements,
        AppPermission.viewAnnouncements,
        AppPermission.manageEvents,
        AppPermission.viewEvents,
        AppPermission.manageClassrooms,
        AppPermission.manageSubjects,
        AppPermission.viewSubjects,
        AppPermission.sendNotifications,
        AppPermission.manageTimetable,
        AppPermission.viewTimetable,
        AppPermission.manageAssignments,
        AppPermission.viewAssignments,
        AppPermission.manageStudyMaterials,
        AppPermission.viewStudyMaterials,
        AppPermission.communicateWithParents,
        AppPermission.manageStudentBehavior,
        AppPermission.viewStudentBehavior,
        AppPermission.manageFees,
      ],
    ),
    RoleDefinition(
      role: UserRole.schoolAdmin,
      permissions: [
        AppPermission.manageUsers,
        AppPermission.manageTeachers,
        AppPermission.manageStudents,
        AppPermission.manageAttendance,
        AppPermission.manageExams,
        AppPermission.viewReports,
        AppPermission.manageFinance,
        AppPermission.manageTransport,
        AppPermission.manageLibrary,
        AppPermission.viewStudents,
        AppPermission.createAnnouncements,
        AppPermission.viewAnnouncements,
        AppPermission.manageEvents,
        AppPermission.viewEvents,
        AppPermission.manageClassrooms,
        AppPermission.manageSubjects,
        AppPermission.viewSubjects,
        AppPermission.sendNotifications,
        AppPermission.manageTimetable,
        AppPermission.viewTimetable,
        AppPermission.manageAssignments,
        AppPermission.viewAssignments,
        AppPermission.manageStudyMaterials,
        AppPermission.viewStudyMaterials,
        AppPermission.communicateWithParents,
        AppPermission.manageStudentBehavior,
        AppPermission.viewStudentBehavior,
        AppPermission.manageFees,
      ],
    ),
    RoleDefinition(
      role: UserRole.chairperson,
      permissions: [
        AppPermission.manageUsers,
        AppPermission.manageTeachers,
        AppPermission.manageStudents,
        AppPermission.manageAttendance,
        AppPermission.manageExams,
        AppPermission.viewReports,
        AppPermission.manageFinance,
        AppPermission.manageTransport,
        AppPermission.manageLibrary,
        AppPermission.viewStudents,
        AppPermission.createAnnouncements,
        AppPermission.viewAnnouncements,
        AppPermission.manageEvents,
        AppPermission.viewEvents,
        AppPermission.manageClassrooms,
        AppPermission.manageSubjects,
        AppPermission.viewSubjects,
        AppPermission.sendNotifications,
        AppPermission.manageTimetable,
        AppPermission.viewTimetable,
        AppPermission.manageAssignments,
        AppPermission.viewAssignments,
        AppPermission.manageStudyMaterials,
        AppPermission.viewStudyMaterials,
        AppPermission.communicateWithParents,
        AppPermission.manageStudentBehavior,
        AppPermission.viewStudentBehavior,
        AppPermission.manageFees,
      ],
    ),
    RoleDefinition(
      role: UserRole.boardMember,
      permissions: [
        AppPermission.manageUsers,
        AppPermission.manageTeachers,
        AppPermission.manageStudents,
        AppPermission.manageAttendance,
        AppPermission.manageExams,
        AppPermission.viewReports,
        AppPermission.manageFinance,
        AppPermission.manageTransport,
        AppPermission.manageLibrary,
        AppPermission.viewStudents,
        AppPermission.createAnnouncements,
        AppPermission.viewAnnouncements,
        AppPermission.manageEvents,
        AppPermission.viewEvents,
        AppPermission.manageClassrooms,
        AppPermission.manageSubjects,
        AppPermission.viewSubjects,
        AppPermission.sendNotifications,
        AppPermission.manageTimetable,
        AppPermission.viewTimetable,
        AppPermission.manageAssignments,
        AppPermission.viewAssignments,
        AppPermission.manageStudyMaterials,
        AppPermission.viewStudyMaterials,
        AppPermission.communicateWithParents,
        AppPermission.manageStudentBehavior,
        AppPermission.viewStudentBehavior,
        AppPermission.manageFees,
      ],
    ),
    RoleDefinition(
      role: UserRole.deanOfAcademics,
      permissions: [
        AppPermission.manageTeachers,
        AppPermission.manageStudents,
        AppPermission.manageAttendance,
        AppPermission.manageExams,
        AppPermission.viewReports,
        AppPermission.viewStudents,
        AppPermission.assignHomework,
        AppPermission.submitHomework,
        AppPermission.viewResults,
        AppPermission.viewSchedule,
        AppPermission.viewExams,
        AppPermission.createAnnouncements,
        AppPermission.viewAnnouncements,
        AppPermission.manageEvents,
        AppPermission.viewEvents,
        AppPermission.manageClassrooms,
        AppPermission.manageSubjects,
        AppPermission.viewSubjects,
        AppPermission.sendNotifications,
        AppPermission.manageTimetable,
        AppPermission.viewTimetable,
        AppPermission.manageAssignments,
        AppPermission.viewAssignments,
        AppPermission.manageStudyMaterials,
        AppPermission.viewStudyMaterials,
        AppPermission.communicateWithParents,
      ],
    ),
    RoleDefinition(
      role: UserRole.departmentHead,
      permissions: [
        AppPermission.manageTeachers,
        AppPermission.manageStudents,
        AppPermission.manageAttendance,
        AppPermission.manageExams,
        AppPermission.viewReports,
        AppPermission.viewStudents,
        AppPermission.assignHomework,
        AppPermission.submitHomework,
        AppPermission.viewResults,
        AppPermission.viewSchedule,
        AppPermission.viewExams,
        AppPermission.createAnnouncements,
        AppPermission.viewAnnouncements,
        AppPermission.manageEvents,
        AppPermission.viewEvents,
        AppPermission.manageClassrooms,
        AppPermission.manageSubjects,
        AppPermission.viewSubjects,
        AppPermission.sendNotifications,
        AppPermission.manageTimetable,
        AppPermission.viewTimetable,
        AppPermission.manageAssignments,
        AppPermission.viewAssignments,
        AppPermission.manageStudyMaterials,
        AppPermission.viewStudyMaterials,
        AppPermission.communicateWithParents,
      ],
    ),
    RoleDefinition(
      role: UserRole.director,
      permissions: [
        AppPermission.manageTeachers,
        AppPermission.manageStudents,
        AppPermission.manageAttendance,
        AppPermission.manageExams,
        AppPermission.viewReports,
        AppPermission.viewStudents,
        AppPermission.assignHomework,
        AppPermission.submitHomework,
        AppPermission.viewResults,
        AppPermission.viewSchedule,
        AppPermission.viewExams,
        AppPermission.createAnnouncements,
        AppPermission.viewAnnouncements,
        AppPermission.manageEvents,
        AppPermission.viewEvents,
        AppPermission.manageClassrooms,
        AppPermission.manageSubjects,
        AppPermission.viewSubjects,
        AppPermission.sendNotifications,
        AppPermission.manageTimetable,
        AppPermission.viewTimetable,
        AppPermission.manageAssignments,
        AppPermission.viewAssignments,
        AppPermission.manageStudyMaterials,
        AppPermission.viewStudyMaterials,
        AppPermission.communicateWithParents,
      ],
    ),
    RoleDefinition(
      role: UserRole.principal,
      permissions: [
        AppPermission.manageTeachers,
        AppPermission.manageStudents,
        AppPermission.manageAttendance,
        AppPermission.manageExams,
        AppPermission.viewReports,
        AppPermission.viewStudents,
        AppPermission.assignHomework,
        AppPermission.submitHomework,
        AppPermission.viewResults,
        AppPermission.viewSchedule,
        AppPermission.viewExams,
        AppPermission.createAnnouncements,
        AppPermission.viewAnnouncements,
        AppPermission.manageEvents,
        AppPermission.viewEvents,
        AppPermission.manageClassrooms,
        AppPermission.manageSubjects,
        AppPermission.viewSubjects,
        AppPermission.sendNotifications,
        AppPermission.manageTimetable,
        AppPermission.viewTimetable,
        AppPermission.manageAssignments,
        AppPermission.viewAssignments,
        AppPermission.manageStudyMaterials,
        AppPermission.viewStudyMaterials,
        AppPermission.communicateWithParents,
      ],
    ),
    RoleDefinition(
      role: UserRole.vicePrincipal,
      permissions: [
        AppPermission.manageTeachers,
        AppPermission.manageStudents,
        AppPermission.manageAttendance,
        AppPermission.manageExams,
        AppPermission.viewReports,
        AppPermission.viewStudents,
        AppPermission.assignHomework,
        AppPermission.submitHomework,
        AppPermission.viewResults,
        AppPermission.viewSchedule,
        AppPermission.viewExams,
        AppPermission.createAnnouncements,
        AppPermission.viewAnnouncements,
        AppPermission.manageEvents,
        AppPermission.viewEvents,
        AppPermission.manageClassrooms,
        AppPermission.manageSubjects,
        AppPermission.viewSubjects,
        AppPermission.sendNotifications,
        AppPermission.manageTimetable,
        AppPermission.viewTimetable,
        AppPermission.manageAssignments,
        AppPermission.viewAssignments,
        AppPermission.manageStudyMaterials,
        AppPermission.viewStudyMaterials,
        AppPermission.communicateWithParents,
      ],
    ),
    RoleDefinition(
      role: UserRole.academicCoordinator,
      permissions: [
        AppPermission.manageTeachers,
        AppPermission.manageStudents,
        AppPermission.manageAttendance,
        AppPermission.manageExams,
        AppPermission.viewReports,
        AppPermission.viewStudents,
        AppPermission.assignHomework,
        AppPermission.submitHomework,
        AppPermission.viewResults,
        AppPermission.viewSchedule,
        AppPermission.viewExams,
        AppPermission.createAnnouncements,
        AppPermission.viewAnnouncements,
        AppPermission.manageEvents,
        AppPermission.viewEvents,
        AppPermission.manageClassrooms,
        AppPermission.manageSubjects,
        AppPermission.viewSubjects,
        AppPermission.sendNotifications,
        AppPermission.manageTimetable,
        AppPermission.viewTimetable,
        AppPermission.manageAssignments,
        AppPermission.viewAssignments,
        AppPermission.manageStudyMaterials,
        AppPermission.viewStudyMaterials,
        AppPermission.communicateWithParents,
      ],
    ),
    RoleDefinition(
      role: UserRole.teacher,
      permissions: [
        AppPermission.viewStudents,
        AppPermission.assignHomework,
        AppPermission.submitHomework,
        AppPermission.viewResults,
        AppPermission.viewSchedule,
        AppPermission.viewExams,
        AppPermission.viewAnnouncements,
        AppPermission.viewEvents,
        AppPermission.viewSubjects,
        AppPermission.communicateWithParents,
        AppPermission.viewAssignments,
        AppPermission.viewStudyMaterials,
      ],
    ),
    RoleDefinition(
      role: UserRole.specialEducator,
      permissions: [
        AppPermission.viewStudents,
        AppPermission.assignHomework,
        AppPermission.submitHomework,
        AppPermission.viewResults,
        AppPermission.viewSchedule,
        AppPermission.viewExams,
        AppPermission.viewAnnouncements,
        AppPermission.viewEvents,
        AppPermission.viewSubjects,
        AppPermission.communicateWithParents,
        AppPermission.viewAssignments,
        AppPermission.viewStudyMaterials,
      ],
    ),
    RoleDefinition(
      role: UserRole.physicalEducationTeacher,
      permissions: [
        AppPermission.viewStudents,
        AppPermission.viewSchedule,
        AppPermission.viewEvents,
        AppPermission.viewAnnouncements,
      ],
    ),
    RoleDefinition(
      role: UserRole.sportsCoach,
      permissions: [
        AppPermission.viewStudents,
        AppPermission.viewSchedule,
        AppPermission.viewEvents,
        AppPermission.viewAnnouncements,
      ],
    ),
    RoleDefinition(
      role: UserRole.musicTeacher,
      permissions: [
        AppPermission.viewStudents,
        AppPermission.viewSchedule,
        AppPermission.viewEvents,
        AppPermission.viewAnnouncements,
      ],
    ),
    RoleDefinition(
      role: UserRole.danceTeacher,
      permissions: [
        AppPermission.viewStudents,
        AppPermission.viewSchedule,
        AppPermission.viewEvents,
        AppPermission.viewAnnouncements,
      ],
    ),
    RoleDefinition(
      role: UserRole.officeAdministrator,
      permissions: [
        AppPermission.manageUsers,
        AppPermission.manageStudents,
        AppPermission.viewStudents,
        AppPermission.viewAnnouncements,
        AppPermission.sendNotifications,
        AppPermission.viewChildReports,
      ],
    ),
    RoleDefinition(
      role: UserRole.receptionist,
      permissions: [
        AppPermission.viewStudents,
        AppPermission.viewAnnouncements,
        AppPermission.sendNotifications,
      ],
    ),
    RoleDefinition(
      role: UserRole.accountant,
      permissions: [
        AppPermission.manageFinance,
        AppPermission.manageFees
      ],
    ),
    RoleDefinition(
      role: UserRole.hrPersonnel,
      permissions: [
        AppPermission.manageUsers,
        AppPermission.manageTeachers,
      ],
    ),
    RoleDefinition(
      role: UserRole.examinationCoordinator,
      permissions: [
        AppPermission.manageExams,
        AppPermission.viewResults,
        AppPermission.viewExams,
        AppPermission.manageTimetable,
        AppPermission.viewTimetable
      ],
    ),
    RoleDefinition(
      role: UserRole.librarian,
      permissions: [
        AppPermission.manageLibrary,
        AppPermission.viewStudents,
        AppPermission.viewAnnouncements,
        AppPermission.viewStudyMaterials
      ],
    ),
    RoleDefinition(
      role: UserRole.labAssistant,
      permissions: [
        AppPermission.viewStudents,
        AppPermission.viewAnnouncements,
        AppPermission.viewStudyMaterials
      ],
    ),
    RoleDefinition(
      role: UserRole.itSupportStaff,
      permissions: [
        AppPermission.manageUsers,
        AppPermission.sendNotifications,
        AppPermission.viewAnnouncements,
      ],
    ),
    RoleDefinition(
      role: UserRole.socialMediaManager,
      permissions: [
        AppPermission.sendNotifications,
        AppPermission.viewAnnouncements,
        AppPermission.viewEvents
      ],
    ),
    RoleDefinition(
      role: UserRole.counselor,
      permissions: [AppPermission.viewStudents, AppPermission.viewStudentBehavior],
    ),
    RoleDefinition(
      role: UserRole.nurse,
      permissions: [
        AppPermission.viewStudents,
        AppPermission.viewAnnouncements,
      ],
    ),
    RoleDefinition(
      role: UserRole.busDriver,
      permissions: [
        AppPermission.viewRoutes,
        AppPermission.viewStudents,
      ],
    ),
    RoleDefinition(
      role: UserRole.busConductor,
      permissions: [
        AppPermission.viewRoutes,
        AppPermission.viewStudents,
      ],
    ),
    RoleDefinition(
      role: UserRole.securityGuard,
      permissions: [
        AppPermission.viewStudents,
        AppPermission.viewAnnouncements,
      ],
    ),
    RoleDefinition(
      role: UserRole.janitor,
      permissions: [],
    ),
    RoleDefinition(
      role: UserRole.electrician,
      permissions: [],
    ),
    RoleDefinition(
      role: UserRole.gardener,
      permissions: [],
    ),
    RoleDefinition(
      role: UserRole.student,
      permissions: [
        AppPermission.submitHomework,
        AppPermission.viewResults,
        AppPermission.viewSchedule,
        AppPermission.viewExams,
        AppPermission.viewAnnouncements,
        AppPermission.viewEvents,
        AppPermission.viewSubjects,
        AppPermission.viewAssignments,
        AppPermission.viewStudyMaterials,
      ],
    ),
    RoleDefinition(
      role: UserRole.parent,
      permissions: [
        AppPermission.viewChildReports,
        AppPermission.viewAttendance,
        AppPermission.payFees,
        AppPermission.viewAnnouncements,
        AppPermission.viewEvents,
        AppPermission.viewSchedule
      ],
    ),
  ];
}